# Generated by Django 4.2.7 on 2025-12-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0007_change_room_id_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waste_bin_images/'),
        ),
    ]
